### ISSUE TITLE
androidx.navigation.safeargs can only be used with an androidx project

### ISSUE THREAD

**Issue by gastsail** [lmj0011/jetpack-release-tracker#3]
I have cloned the project and run out of this error while syncing gradle

`androidx.navigation.safeargs can only be used with an androidx project`

I have seen the gradle properties, and the two build gradle files and it seems like it does not contain any problems, but for some reason this error is thrown every time, I have also changed from

`apply plugin: "androidx.navigation.safeargs"`

to

`apply plugin: "androidx.navigation.safeargs.kotlin"`

Since is the plugin for kotlin but that is also not working

**Comment by lmj0011** [comment]
create a `gradle.properties` file from the `gradle.properties.example`

ie.) `cp gradle.properties.example gradle.properties `

https://github.com/lmj0011/jetpack-release-tracker/blob/master/gradle.properties.example

**Comment by gastsail** [comment]
Thanks, it solved the issue, I'm working on some code improvements to do a pull request later :)
