### ISSUE TITLE
Latest version not reflected

### ISSUE THREAD

**Issue by crjacinro** [lmj0011/jetpack-release-tracker#6]
Hi, 

I installed the app from Playstore and upon checking some version are not yet updated. 

For example: compose is already **1.0.0-alpha04** but the app is still showing **1.0.0-alpha03**.

https://developer.android.com/jetpack/androidx/releases/compose

Thanks.

**Comment by lmj0011** [comment]
looks like some artifact renaming happened at [v0.1.0-dev14](https://developer.android.com/jetpack/androidx/releases/ui#0.1.0-dev14)

In the next app release, it will be following `androidx.compose.ui`
https://developer.android.com/jetpack/androidx/releases/compose-ui

see https://github.com/lmj0011/jetpack-release-tracker/commit/50c42c76cf89d6942346b73d50cdeec18825822e

**Comment by crjacinro** [comment]
I have pulled your changes and ran the app from dev branch. Works fine! Thanks.
