### ISSUE TITLE
androidx.datastore missing

### ISSUE THREAD

**Issue by dmelton-gpsw** [lmj0011/jetpack-release-tracker#8]
I'm looking here for the new library androidx.datastore and noticed it's missing!

https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?m=1

**Comment by lmj0011** [comment]
I'm currently busy with another project and will not be back to this one for some time. Feel free to submit a PR.

As for the missing library, all you will need to do is add a new entry for it in [this file](https://github.com/lmj0011/jetpack-release-tracker/blob/master/app/src/main/java/name/lmj0011/jetpackreleasetracker/helpers/AndroidXLibraryDataset.kt)

https://maven.google.com/web/index.html has the info needed to complete this.

**Comment by lmj0011** [comment]
apk with the patch is [available](https://github.com/lmj0011/jetpack-release-tracker/releases/tag/v1.2.3-beta.1)

will be pushed to production soon
