### ISSUE TITLE
Unable to track stable versions only in project tracker

### ISSUE THREAD

**Issue by yashovardhan99** [lmj0011/jetpack-release-tracker#9]
Enabling stable versions only with a valid URL is crashing the app.

Apperantly, I can enable it with a wrong url and then changing to the correct url will crash the app.

- My deps.list - https://raw.githubusercontent.com/yashovardhan99/HealersDiary/master/app/deps.list.txt
- App version - 1.2.1
- Device - OnePlus 5 (API 29)

**Comment by lmj0011** [comment]
apk with the patch is [available](https://github.com/lmj0011/jetpack-release-tracker/releases/tag/v1.2.3-beta.1)
